# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [cbd, , Socal, FCC]
patreon: # Replace with a single Patreon username 
open_collective: # Replace with a single Open Collective username opensea.io
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username turbo
issuehunt: # Replace with a single IssueHunt username snoopy
otechie: # Replace with a single Otechie username arcangel 
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://keeps.com','https://ulta.com','https://icann.org']
